### ISSUE TITLE
support multi-day averages in `clockPlotBase()`

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/PWFSLSmokePlots#13]
This will involve addressing the `TODO` statements in sections: "Time limits" and "Clock data".

The resulting `clockData$pm25` column should contain the time-of-day multi-day average.

**Comment by tabrasel** [comment]
A question about cases where the `enddate` argument is defined, but `startdate` is not:

Should a call like `clockPlotBase(ws_monitor, enddate =  "2016-08-10")` generate a plot spanning the day of August 9th (ending at the given date), or a plot spanning the day of August 10th (same as `clockPlotBase(ws_monitor, startdate =  "2016-08-10")`)?

Or something else?
