### ISSUE TITLE
move older clockPlot code back in as "pwfsl_clockPlot"

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/PWFSLSmokePlots#26]
The older `clockPlot_` code is highly tailored to PWFSL styling requests and this would be difficult to replicate with Helen's newer, more generic code. 

The older code should be brought in and renamed with a `pwfsl_` prefix to identify it as specific to PWFSL needs and not part of the more generic suite of functionality.

**Comment by spencerpease** [comment]
We are moving forward with a different naming scheme
