### ISSUE TITLE
Create color scales for smoke visualizations

### ISSUE THREAD

**Issue by spencerpease** [MazamaScience/PWFSLSmokePlots#3]
Common scales we would use include:

- Discrete AQI colors (standard)
- Discrete AQI colors (muted)
- Continuous gray for PM2.5 values

**Comment by jonathancallahan** [comment]
I think that generation of color palettes should be handled in *PWFSLSmoke* plots so that both base plot functions (in PWFSLSmoke) and ggplot functions (in *PWFSLSmokePlots*) can have access to them.

I already have a skeletal `aqiColors()` function in *PWFSLSmokePlots* to address this.
